"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const roles_service_1 = __importDefault(require("./roles.service"));
const roles_controller_1 = __importDefault(require("./roles.controller"));
const auth_middleware_1 = require("../../middleware/auth.middleware");
const permission_middleware_1 = require("../../middleware/permission.middleware");
const resources_1 = require("../../../common/lib/resources");
const roleRouter = (0, express_1.Router)();
const roleService = new roles_service_1.default();
const roleController = new roles_controller_1.default(roleService);
const resource = resources_1.Resource.ROLES;
roleRouter.post('/', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'w'), roleController.addRole);
roleRouter.get('/', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'r'), roleController.getAllRoles);
roleRouter.get('/:roleId', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'r'), roleController.getRoleById);
roleRouter.patch('/:roleId', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'w'), roleController.updateRole);
roleRouter.delete('/:roleId', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'x'), roleController.deleteRole);
exports.default = roleRouter;
