"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const games_controller_1 = require("./games.controller");
const games_service_1 = require("./games.service");
const multer_1 = __importDefault(require("multer"));
const auth_middleware_1 = require("../../middleware/auth.middleware");
const permission_middleware_1 = require("../../middleware/permission.middleware");
const resources_1 = require("../../../common/lib/resources");
const gamesRoutes = express_1.default.Router();
const gamesController = new games_controller_1.GameController(new games_service_1.GameService());
const upload = (0, multer_1.default)({ storage: multer_1.default.memoryStorage(), limits: { fileSize: 50 * 1024 * 1024 } });
const resource = resources_1.Resource.GAMES;
gamesRoutes.post('/', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'w'), upload.fields([{ name: 'thumbnail', maxCount: 1 }, { name: 'payout', maxCount: 1 }]), gamesController.createGame);
gamesRoutes.get('/', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'r'), gamesController.getGames);
gamesRoutes.post('/upload', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'w'), upload.fields([{ name: 'games', maxCount: 1 }]), gamesController.uploadGames);
gamesRoutes.get('/download', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'r'), gamesController.downloadGames);
gamesRoutes.put('/reorder', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'w'), gamesController.reorderGames);
gamesRoutes.get('/:id', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'r'), gamesController.getGame);
gamesRoutes.get('/:id/payouts', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'r'), gamesController.getGamePayouts);
gamesRoutes.patch('/:id/payouts/:payoutId', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'w'), gamesController.activateGamePayout);
gamesRoutes.delete('/:id/payouts/:payoutId', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'x'), gamesController.deleteGamePayout);
gamesRoutes.put('/:id', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'w'), upload.fields([{ name: 'thumbnail', maxCount: 1 }, { name: 'payout', maxCount: 1 }]), gamesController.updateGame);
gamesRoutes.delete('/:id', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'x'), gamesController.deleteGame);
gamesRoutes.get('/tag/:tag', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'r'), gamesController.getGame);
gamesRoutes.get('/slug/:slug', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'r'), gamesController.getGame);
gamesRoutes.get('/slug/:slug/play', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'r'), gamesController.playGame);
gamesRoutes.get('/name/:name', auth_middleware_1.authHandler, (0, permission_middleware_1.checkPermission)(resource, 'r'), gamesController.getGame);
exports.default = gamesRoutes;
