name: Build and Deploy

on:
  push:
    branches:
      - "dev"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create and Push dev-build Branch
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          git checkout dev
          git checkout -b dev-build

          # Configure Git user
          git config --global user.email "mohitnegi.trippybug@gmail.com"
          git config --global user.name "TrippyMohit"

          # Stash untracked changes
          git stash -u

          # Copy built files
          mkdir -p ./build-artifacts/src
          cp -r ./dist/src/* ./build-artifacts/src/
          cp ./dist/server.js ./build-artifacts/

          # Remove unnecessary files
          rm -rf ./dist ./node_modules ./server.ts

          # Delete all .ts files from src
          find ./build-artifacts/src -name "*.ts" -type f -delete

          # Stage and commit changes
          git add -f ./build-artifacts
          git commit -m "Add new build artifacts" || echo "No changes to commit"

          # Push to dev-build branch
          git push origin dev-build --force
